# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Mobirise.Mobirise
PackageVersion: 5.5.5
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.mobirise.com/MobiriseSetup.exe
  InstallerSha256: F504D1413FEBB6BA2D6334A46917DBD00776C622F2C71F3B39EA8FC1D0AD066E
ManifestType: installer
ManifestVersion: 1.1.0
