# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: UnityTechnologies.Unity.2021
PackageVersion: 2021.2.5f1
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x64
    MinimumVersion: 10.0.30319
  - PackageIdentifier: Microsoft.VC++2013Redist-x64
    MinimumVersion: 12.0.30501.0
  - PackageIdentifier: Microsoft.VC++2015Redist-x64
    MinimumVersion: 14.0.23026.0
Installers:
- Architecture: x64
  InstallerUrl: https://download.unity3d.com/download_unity/4ec9a5e799f5/Windows64EditorInstaller/UnitySetup64-2021.2.5f1.exe
  InstallerSha256: F60F00FE6C75C7E844C77495FC019F0A746BDF81FCC7D7E414CE4E61C946FDF6
ManifestType: installer
ManifestVersion: 1.0.0

