# Automatically updated by the winget bot at 2021/Nov/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Wondershare.DemoCreator
PackageVersion: 5.4.0.6
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/democreator_full7743.exe
  InstallerSha256: AB3AF1DC93915318B80927575C1C64472B4B78BE045EC4BCB1D287D1704A68FF
ManifestType: installer
ManifestVersion: 1.0.0
