# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: M2Team.NanaZip
PackageVersion: 1.0.88.0
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.17763.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/1.0-Preview4/40174MouriNaruto.NanaZipPreview_1.0.88.0_gnj4mf6z9tkrc.msixbundle
  InstallerSha256: 0064DB91F6B8AC68C7214C48171E639A4298132A1DFFFBA3ACBE338CD6D7FAE7
  SignatureSha256: A4A37E4BA79EC8C0B3573A3E3384433FD09D28127290BE7275D2FDDEBFCBAC84
  PackageFamilyName: 40174MouriNaruto.NanaZipPreview_gnj4mf6z9tkrc
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.17763.0
  Architecture: x86
  InstallerType: msix
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/1.0-Preview4/40174MouriNaruto.NanaZipPreview_1.0.88.0_gnj4mf6z9tkrc.msixbundle
  InstallerSha256: 0064DB91F6B8AC68C7214C48171E639A4298132A1DFFFBA3ACBE338CD6D7FAE7
  SignatureSha256: A4A37E4BA79EC8C0B3573A3E3384433FD09D28127290BE7275D2FDDEBFCBAC84
  PackageFamilyName: 40174MouriNaruto.NanaZipPreview_gnj4mf6z9tkrc
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.17763.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/1.0-Preview4/40174MouriNaruto.NanaZipPreview_1.0.88.0_gnj4mf6z9tkrc.msixbundle
  InstallerSha256: 0064DB91F6B8AC68C7214C48171E639A4298132A1DFFFBA3ACBE338CD6D7FAE7
  SignatureSha256: A4A37E4BA79EC8C0B3573A3E3384433FD09D28127290BE7275D2FDDEBFCBAC84
  PackageFamilyName: 40174MouriNaruto.NanaZipPreview_gnj4mf6z9tkrc
ManifestType: installer
ManifestVersion: 1.0.0

