# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: JetBrains.IntelliJIDEA.Ultimate.EAP
PackageVersion: 213.6461.21
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/idea/ideaIU-213.6461.21.exe
  InstallerSha256: B96603835D39A568DA65C753DDF084CEBA402369140D60F6FF5585D432837011
ManifestType: installer
ManifestVersion: 1.1.0
