# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: JetBrains.RubyMine.EarlyAccess
PackageVersion: 213.6461.24
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/ruby/RubyMine-213.6461.24.exe
  InstallerSha256: E66BA9112822BD25ADF236D4C1B74A80039D1CD684FCCA30A99DA0C26B2A3541
ManifestType: installer
ManifestVersion: 1.1.0
