# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: schild-report.schild-report
PackageVersion: 16.16.3
InstallerLocale: de-DE
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/schemacrawler/SchemaCrawler-Installers/releases/download/v16.16.3/SchemaCrawler-16.16.3.msi
  InstallerSha256: ED88F2236702A2C2558FE521E1FB3B1ED7DAB7DD8831566084C09B2C345B9736
ManifestType: installer
ManifestVersion: 1.1.0
