# Automatically updated by the winget bot at 2021/Nov/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Fork.Fork
PackageVersion: 1.69.4
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://git-fork.com/update/win/ForkInstaller.exe
  InstallerSha256: 25296C3256C412E5E1C6AB287F2F711474C3A4F71838D05227E40B32279DE22F
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
