# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: valinet.ExplorerPatcher.Prerelease
PackageVersion: 22000.376.40.12
MinimumOSVersion: 10.0.0.0
InstallerType: inno
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/valinet/ExplorerPatcher/releases/download/22000.376.40.12_c0372a0/ep_setup.exe
  InstallerSha256: AB1FC9A55A610E94E31CD1F049B4987C3138BC2D13F31E7E26F4301458423F6F
  ProductCode: '{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_ExplorerPatcher'
ManifestType: installer
ManifestVersion: 1.1.0
