# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: calibre.calibre.portable
PackageVersion: 5.34.0.0
MinimumOSVersion: 10.0.0.0
InstallerType: exe
InstallerSwitches:
  Silent: /CalibrePortable/
  SilentWithProgress: /CalibrePortable/
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/kovidgoyal/calibre/releases/download/v5.34.0/calibre-portable-installer-5.34.0.exe
  InstallerSha256: E7B366B2F867FFF6E74727A5B5659C0070771F85D0047C224D075B8DCEAEF2D7
ManifestType: installer
ManifestVersion: 1.1.0
