# Automatically updated by the winget bot at 2021/Dec/02
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Huawei.Welink
PackageVersion: 7.11.13
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://obs-client.obs.cn-north-1.myhuaweicloud.com/WeLink_setup.exe
  InstallerSha256: 520ECDB4644FFAFE94071322BB9D9BC09B202F0264A97979ADDDCA198CC174C7
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
