# Automatically updated by the winget bot at 2021/Dec/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: WhatsApp.WhatsApp.Beta
PackageVersion: 2.2147.11
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/x64/WhatsAppSetup-beta.exe
  InstallerSha256: 7562BD3DDF15D3B9C512260FCB6AE80EC5DABCDA876856682A6D22BEBEBF82A8
- Architecture: x86
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/ia32/WhatsAppSetup-beta.exe
  InstallerSha256: 9D6184B1B8495B1AB581638BA3DC852A09155C064CB99A191C88F85576662565
ManifestType: installer
ManifestVersion: 1.0.0
