# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: JetBrains.WebStorm.EAP
PackageVersion: 213.6461.19
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/webstorm/WebStorm-213.6461.19.exe
  InstallerSha256: 5D937BA5C43877707E77798A3BB7A335B382CCB36CAAFC9ED257F19017CE6DBE
ManifestType: installer
ManifestVersion: 1.1.0
