# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Playnite.Playnite
PackageVersion: "9.12"
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /NORESTART
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://playnite.link/update/stable/9.12/Playnite912.exe
  InstallerSha256: 503CA0693DE6AFF04DD921AC640503D8F0E8D5E17262FC78B29C4CDB4EEB4E4C
ManifestType: installer
ManifestVersion: 1.1.0
