# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Wondershare.PDFelement
PackageVersion: 8.3.5
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- pdf
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/pdfelement-pro_full5239.exe
  InstallerSha256: 3F6C0E06D777D954810E437189EA258036B54CC73481F2D55550B0E71E230AF6
ManifestType: installer
ManifestVersion: 1.1.0
