# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome.Beta
PackageVersion: 97.0.4692.56
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: B80CA98B3CDFB244BC06BDD0B0B92B3C4B42A30D699289FB98143FC4B8DE9D68
  ProductCode: '{8680F70A-9C02-31C1-9589-95969877C1E6}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: E235BEC8C8225FE09AABD728E2710308B30BB024C3657DCF6060029E2B8C9A4A
  ProductCode: '{789ED314-BD17-3587-BDBA-F1C2CA7B60A7}'
ManifestType: installer
ManifestVersion: 1.1.0
