# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Spotify.Spotify
PackageVersion: 1.1.74.631.g0b24d9ad
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: /Silent
  SilentWithProgress: /Silent
UpgradeBehavior: install
ElevationRequirement: elevationProhibited
Installers:
- Architecture: x86
  InstallerUrl: https://download.scdn.co/SpotifyFullSetup.exe
  InstallerSha256: 0487AB89C97078FD75582EE8C7A8CADBCD2692DDF14BBC9C5E960861ADDFFD46
ManifestType: installer
ManifestVersion: 1.1.0
