# Created with YamlCreate.ps1 v2.0.3 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Tutanota.Tutanota
PackageVersion: 3.89.23
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: neutral
  Scope: user
  InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
  InstallerSha256: 79AD32D3787FD16B37F6BF828356BBA9D7EA0DF6ECF5C16B77660402AD3CC6F6
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: neutral
  Scope: machine
  InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
  InstallerSha256: 79AD32D3787FD16B37F6BF828356BBA9D7EA0DF6ECF5C16B77660402AD3CC6F6
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
