# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 3.4.0.20211129
PackageLocale: en-US
Publisher: Nextcloud GmbH
PublisherUrl: https://nextcloud.com
PublisherSupportUrl: https://github.com/nextcloud/desktop/issues
PrivacyUrl: https://nextcloud.com/privacy
Author: Nextcloud GmbH
PackageName: Nextcloud
PackageUrl: https://nextcloud.com
License: GNU GENERAL PUBLIC LICENSE Version 2
LicenseUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
Copyright: Copyright (C) 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
ShortDescription: The Nextcloud Desktop Client is a tool to synchronize files from Nextcloud Server with your computer.
Description: Use the desktop clients to keep your files synchronized between your Nextcloud server and your desktop. Select one or more directories on your local machine and always have access to your latest files wherever you are.
Moniker: nextclouddesktop
Tags:
- utility
- cloud
- synchronization
- cloud-sync
- nextcloud-desktop-client
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
