# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 3.4.0.20211129
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: Reboot=ReallySuppress
InstallerSuccessCodes:
- 3010
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nextcloud/desktop/releases/download/v3.4.0/Nextcloud-3.4.0-x64.msi
  InstallerSha256: 6C2A180D933E0F7BBEEE5FCF012FA4226FC63B02F5AEDBC6209D0B5DB2AAE33C
  ProductCode: '{F8A0EB53-F277-4267-ACF7-F4CBCC87DF61}'
- Architecture: x86
  InstallerUrl: https://github.com/nextcloud/desktop/releases/download/v3.4.0/Nextcloud-3.4.0-x86.msi
  InstallerSha256: 634A9C12CED322256ED045A208B3AC62AF55C98F0069EA19CBDAF5308C68DBB9
  ProductCode: '{D24008C5-EC60-49E9-9641-0DDAC58389E3}'
ManifestType: installer
ManifestVersion: 1.1.0
