# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 3.4.0.20211129
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
