# Automatically updated by the winget bot at 2021/Dec/13
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GeoGebra.CalculatorSuite
PackageVersion: 6.0.680
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.geogebra.org/package/win-suite
  InstallerSha256: F5F14E04BC7838C9028D0418083207FB192723B6DF68935D21F2CB7BCFEDDB03
ManifestType: installer
ManifestVersion: 1.0.0
