# Automatically updated by the winget bot at 2021/Dec/18
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Telerik.Fiddler
PackageVersion: 5.0.20211.51073
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
