# Created with YamlCreate.ps1 v2.0.3 $debug=NVS1.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ChronoplexSoftware.MyFamilyTree
PackageVersion: 11.1.3.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- aft
- afz
- agz
- aq
- dat
- family
- familyx
- familyxs
- fbk
- fdb
- fow
- ftb
- ftw
- gdz
- ged
- indiv2.dat
- mft
- nam
- paf
- pjc
- RM8
- RMB8
- rmg
- rmgb
- rmgc
- sqz
- tmg
- tre
- uzed
- ver
- zed
- zip
Installers:
- Architecture: x64
  InstallerUrl: https://chronoplexsoftware.com/myfamilytree/downloads/myfamilytree11.1.3.0x64.msi
  InstallerSha256: 489517BAC4E6A44365FE338AFEE27107B0432CA940B53E2303A5518965FD8E1C
  ProductCode: '{CA77209F-F195-4C05-B88D-769F3DD6DF7A}'
- Architecture: x86
  InstallerUrl: https://chronoplexsoftware.com/myfamilytree/downloads/myfamilytree11.1.3.0.msi
  InstallerSha256: AC40E8367EAF03D0D57BAC9AA16FD15E7E889F9616A90885D4A1B5AD0C9B24B4
  ProductCode: '{05EEB66F-84B3-4689-AD74-96A6E54FD8ED}'
ManifestType: installer
ManifestVersion: 1.1.0
