# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.4.6.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- aws
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.4.6.msi
  InstallerSha256: F5781BFFE85342D71114C37D8CCB501B7852DA2F79D2323504233B6363722240
  ProductCode: '{A65774DE-E695-4D3C-84D5-705592A51F0C}'
ManifestType: installer
ManifestVersion: 1.1.0
