# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer
PackageVersion: 15.25.8
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup_x64.exe
  InstallerSha256: EFA1B635356EF73D7A61486BA89401B46CC7CF5A71F7D179BEAFE59152B2F8F6
- Architecture: x86
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup.exe
  InstallerSha256: F2696153DEDF3516C0AECE3D8BE9844B0D3654F3BD405A4E496CC2CCC3A38702
ManifestType: installer
ManifestVersion: 1.1.0
