# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Blueberry.FlashbackExpress
PackageVersion: 5.54.0.4702
PackageLocale: en-US
Publisher: Blueberry Software (UK) Ltd.
PublisherUrl: https://www.flashbackrecorder.com/
PublisherSupportUrl: https://www.flashbackrecorder.com/support/
PrivacyUrl: https://www.flashbackrecorder.com/privacypolicy/
Author: Blueberry Software (UK) Ltd.
PackageName: FlashBack Express
PackageUrl: https://www.flashbackrecorder.com/express/
License: Proprietary
LicenseUrl: https://www.flashbackrecorder.com/end-user-agreement-express/
Copyright: Copyright (c) Blueberry Software (UK) Ltd. All rights reserved.
CopyrightUrl: https://www.flashbackrecorder.com/aboutus/
ShortDescription: FlashBack Express Screen Recorder
Description: Blueberry FlashBack Express Screen Recorder for Windows
Moniker: flashback.express
Tags:
- flashback
- flashback-express
- flashback-express-5
ManifestType: defaultLocale
ManifestVersion: 1.0.0

