# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Blueberry.FlashbackExpress
PackageVersion: 5.54.0.4702
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

