# Automatically updated by the winget bot at 2021/Nov/24
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.164.5052
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x86
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
Installers:
- Architecture: x64
  InstallerUrl: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe
  InstallerSha256: 4AC0D3DA7F96DA8E7CBB9421418EC9A05599B3B507E03D0CE5A03AEA51257367
ManifestType: installer
ManifestVersion: 1.0.0
