# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.Teams.Preview
PackageVersion: 1.4.00.32771
MinimumOSVersion: 10.0.0.0
Scope: user
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.32771/Teams_windows_x64.exe
  InstallerSha256: E2721F16BFB5C38A1BB6CACBD0779142C3736DCF2CA79AF161827F0E85FCAEC1
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.32771/Teams_windows_x64.msi
  InstallerSha256: F247D0F8D5F0A118B48F5D0CEC02E164CCA2BA4E4E74119F035F3906B88C343B
  ProductCode: '{731F6BAA-A986-45A4-8936-7C3AAAAA760B}'
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows/1.4.00.32771/Teams_windows.exe
  InstallerSha256: 678275F7A5A59A3C8B9C9C827E3724D17093A24556ABCBF5CB12EAFCED8F1EF1
ManifestType: installer
ManifestVersion: 1.1.0
