# Created with YamlCreate.ps1 v2.0.3 $debug=QUSU.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Prey.Prey
PackageVersion: 1.9.14
PackageLocale: en-US
Publisher: Prey, Inc.
PublisherUrl: https://preyproject.com/
PublisherSupportUrl: https://help.preyproject.com/
PrivacyUrl: https://preyproject.com/privacy/
# Author: 
PackageName: Prey Anti-Theft
PackageUrl: https://github.com/prey/prey-node-client
License: GPL-3.0-only
LicenseUrl: https://github.com/prey/prey-node-client/blob/master/license.txt
# Copyright: 
# CopyrightUrl: 
ShortDescription: Basic Anti-Theft program.
# Description: 
Moniker: prey
Tags:
- data
- protection
- anti-theft
- retrieve
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
