# Automatically updated by the winget bot at 2021/Nov/27
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Typora.Typora
PackageVersion: 1.0.2
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /NORESTART
UpgradeBehavior: install
FileExtensions:
- md
- mmd
- mkd
- mdwn
- mdown
- mdx
- mdtxt
- mdtext
- apib
- rmd
- txt
- text
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://typora.io/windows/typora-setup-x64.exe
  InstallerSha256: E1A1175548B042FE6C6E21E74A7B7F9472B8E6C485838ECD4CBC9899A9C7BD21
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://typora.io/windows/typora-setup-x64.exe
  InstallerSha256: E1A1175548B042FE6C6E21E74A7B7F9472B8E6C485838ECD4CBC9899A9C7BD21
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x86
  Scope: user
  InstallerUrl: https://typora.io/windows/typora-setup-ia32.exe
  InstallerSha256: D35302BF52A1673C552F347C4BE8854F98694A7F3719EE24E3812F7D85DAEA31
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://typora.io/windows/typora-setup-ia32.exe
  InstallerSha256: D35302BF52A1673C552F347C4BE8854F98694A7F3719EE24E3812F7D85DAEA31
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: arm64
  Scope: user
  InstallerUrl: https://typora.io/windows/typora-setup-arm64.exe
  InstallerSha256: 83DE3D4F1F49E50029DE7C5A4A0191FAD39471FF08F3A7B835648BA3314AC3B3
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://typora.io/windows/typora-setup-arm64.exe
  InstallerSha256: 83DE3D4F1F49E50029DE7C5A4A0191FAD39471FF08F3A7B835648BA3314AC3B3
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.0.0
