# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: GOMLab.GOMPlayer
PackageVersion: 2.3.72.5336
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://cdn.gomlab.com/gretech/player/GOMPLAYERGLOBALSETUP_CHROME.EXE
  InstallerSha256: 70075BC969EB316BF067B355BE9BD0D9DF7ED2B81E6BE7C001D18798A7C98CB7
ManifestType: installer
ManifestVersion: 1.1.0
