# Created with YamlCreate.ps1 v2.0.2 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.99.862.0
Platform:
- Windows.Desktop
MinimumOSVersion: 8.1.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -quiet -norestart
  SilentWithProgress: -passive -norestart
  Custom: ACCEPT_EULA=1
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup.exe
  InstallerSha256: 4D9B8217479FAC1DA9102F5B2E1FE97C849A52C218127A0C3E9174A8793B84B4
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  InstallerSha256: CD6C64916BE377D6303E82277FE983A5E0D1E4A6D095D22C538C76DBDC35BD87
ManifestType: installer
ManifestVersion: 1.1.0
