# Created with YamlCreate.ps1 v2.0.0 $debug=MDSU.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly
PackageVersion: 96.0a1
PackageLocale: en-US
Publisher: Mozilla
PublisherUrl: https://www.mozilla.org/
PublisherSupportUrl: https://support.mozilla.org/products
PrivacyUrl: https://www.mozilla.org/privacy/firefox/
# Author: 
PackageName: Nightly
PackageUrl: https://www.mozilla.org/firefox/channel/desktop/#nightly
License: MPL-2.0
LicenseUrl: https://www.mozilla.org/en-US/MPL/2.0/
# Copyright: 
# CopyrightUrl: 
ShortDescription: Nightly is an unstable testing and development version of Firefox.
# Description: 
Moniker: firefox-nightly
Tags:
- browser
- web-browser
- open-source
- cross-platform
- foss
- nightly
- gecko
ManifestType: defaultLocale
ManifestVersion: 1.0.0

