# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: NimbusWeb.NimbusNote
PackageVersion: 8.3.7
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://nimbusweb.me/nimbusnote.exe
  InstallerSha256: 3925F4C07F7CF772A9C349DE3BB45781D22647FCDB9D0C796B952643B28C9AC2
ManifestType: installer
ManifestVersion: 1.1.0
