# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.41.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.41.0/nu_0_41_0_windows.msi
  InstallerSha256: B57AD484993DE3E9975293B3DC4598DAEB7F45917B0EDC287C2521D40C05501D
  ProductCode: '{31846932-A450-4703-A0FB-6DC815D1E137}'
ManifestType: installer
ManifestVersion: 1.0.0

