# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: raimo.Smallpdf
PackageVersion: 3.0.1.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download.smallpdf.com/desktop-windows/Smallpdf.msi
  InstallerSha256: C4305AB3CC0A2604E800B043B75D68FD444B3CF82A705FBF8AD8598789BDE6BA
  ProductCode: '{CF0EA234-B1A7-45AC-9AFF-4B7C0AA65020}'
ManifestType: installer
ManifestVersion: 1.1.0
