# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Malwarebytes.Malwarebytes
PackageVersion: 4.5.0.152
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /VERYSILENT
  SilentWithProgress: /VERYSILENT
  Custom: /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe
  InstallerSha256: B9C7A34CB7FEFD216FD63875CA12E68A92DDA449002AFB06CB1BEEC5C3F0A432
ManifestType: installer
ManifestVersion: 1.1.0
