# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: IObit.AdvancedSystemCare
PackageVersion: 15.1.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://cdn.iobit.com/dl/advanced-systemcare-setup.exe
  InstallerSha256: FE00A5ADE86F6AB1F7531B3F11DC15A23C4BD37A113758424011501A8C0E1434
ManifestType: installer
ManifestVersion: 1.1.0
