# Created with YamlCreate.ps1 v2.0.3 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: NordPassTeam.NordPass
PackageVersion: 4.15.31
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.npass.app/windows/NordPassSetup.exe
  InstallerSha256: A8BFE19CA184E2B8102EA79BBA39559C59DA99A2E7324C350C2DE522CFB48583
- Architecture: x86
  InstallerUrl: https://downloads.npass.app/windows_x86/NordPassSetup_x86.exe
  InstallerSha256: 724A89DEC0E13DE220A4BA420A0C2ECF75738BF327CE818DB7C290489666D368
ManifestType: installer
ManifestVersion: 1.1.0
