# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: HiBitSoftware.HiBitUninstaller
PackageVersion: 2.7.15.100
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://www.hibitsoft.ir/HiBitUninstaller/HiBitUninstaller-setup.exe
  InstallerSha256: 923FFF900D307493482B48DE14156C2796105572EB8D2F415E4EB3AB6A6FE1F6
ManifestType: installer
ManifestVersion: 1.1.0
