# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: PTRTECH.UVtools
PackageVersion: 2.27.0
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/sn4k3/UVtools/releases/download/v2.27.0/UVtools_win-x64_v2.27.0.msi
  InstallerSha256: DA15D7EC8892A671EACA6A7F3DF20AE3F5478C53C75A57BBA46EA16E5CE79192
  ProductCode: '{E58DFA6F-343C-481B-8D92-B325F3544060}'
ManifestType: installer
ManifestVersion: 1.0.0

