# Automatically updated by the winget bot at 2021/Dec/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.PowerAutomateDesktop
PackageVersion: 2.15.284.21354
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
  Custom: -accepteula
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/b/d/8/bd8409df-7b80-4ef7-89c5-5a7a941a5093/Setup.Microsoft.PowerAutomate.exe
  InstallerSha256: 65140FBF3F0CBC89B5D930C195B501318E2E436B894B51937B4123D3C2DB0C13
ManifestType: installer
ManifestVersion: 1.1.0
