PackageIdentifier: LutzRoeder.Netron
PackageVersion: 5.4.0
Platform:
- Windows.Desktop
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x86
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.4.0/Netron-Setup-5.4.0.exe
  InstallerSha256: 0339DD29E346E2027A0BFB46BF5E517CB672F19620B290D1921A1179B08AE3D2
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- Architecture: arm64
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.4.0/Netron-Setup-5.4.0.exe
  InstallerSha256: 0339DD29E346E2027A0BFB46BF5E517CB672F19620B290D1921A1179B08AE3D2
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
FileExtensions:
- armnn
- caffemodel
- cmf
- dnn
- h5
- hd5
- hdf5
- keras
- lite
- mar
- meta
- mlmodel
- mlpackage
- mnn
- model
- nb
- nn
- om
- onnx
- paddle
- param
- pb
- pbtxt
- pdmodel
- pdparams
- prototxt
- pt
- pth
- ptl
- rknn
- t7
- tfl
- tflite
- tmfile
- uff
- xmodel
ManifestType: installer
ManifestVersion: 1.0.0
