# Automatically updated by the winget bot at 2021/Nov/28
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: KCSoftwares.SUMo
PackageVersion: 5.14.5.512
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
FileExtensions:
- txt
- csv
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://kcsoftwares.com/files/sumo_lite.exe
  InstallerSha256: D715AFDDF1C9C239F5CF6A5D054BA349E8C9728C74E1EB709F57E593D3301F01
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
