# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Figma.Figma
PackageVersion: 107.1.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://desktop.figma.com/win/FigmaSetup.exe
  InstallerSha256: 82847827DC8FEEDE4664220E0AEC3B98C546E47B72F324F7C736802EAC6D7B86
ManifestType: installer
ManifestVersion: 1.1.0
