# Automatically updated by the winget bot at 2021/Nov/24
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Amazon.WorkspacesClient
PackageVersion: 4.0.5.2379
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://d2td7dqidlhjx7.cloudfront.net/prod/global/windows/Amazon+WorkSpaces.msi
  InstallerSha256: C2D95119F275FC57790559D7030B325E630D57B6637740B75DC7D3F5B14712A5
  UpgradeBehavior: install
  ProductCode: '{C749EFEB-72F5-497E-BB29-5639500047F5}'
ManifestType: installer
ManifestVersion: 1.0.0
