# Automatically updated by the winget bot at 2021/Nov/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Nord.NordLocker
PackageVersion: 2.2.14.2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
