# Automatically updated by the winget bot at 2021/Nov/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Nord.NordLocker
PackageVersion: 2.2.14.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /SILENT
  SilentWithProgress: /SILENT
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
Installers:
- Architecture: neutral
  InstallerUrl: https://downloads.nordcdn.com/apps/windows/NordLocker/NordLockerSetup.exe
  InstallerSha256: 3095F67AB32944066DFC0F579E38F08898D193C7C629BCF9548D3D08A7294DE7
ManifestType: installer
ManifestVersion: 1.0.0
