# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: BrickLink.Studio
PackageVersion: "2.0"
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallerSwitches:
  Custom: /norestart
Installers:
- Architecture: x64
  InstallerUrl: https://s3.amazonaws.com/blstudio/Studio2.0/Studio+2.0.exe
  InstallerSha256: FBB3EECE8AB2000D7B948054ABFCB021C96A9259BD99CFD76C1DDECF1EEB7051
ManifestType: installer
ManifestVersion: 1.1.0
