# Created with YamlCreate.ps1 v2.0.0 $debug=QUSU.7-1-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json

PackageIdentifier: Tencent.WeChat
PackageVersion: 3.4.5.27
PackageLocale: zh-CN
Publisher: 腾讯科技(深圳)有限公司
PublisherUrl: https://weixin.qq.com
PublisherSupportUrl: https://kf.qq.com/product/weixin.html
PrivacyUrl: https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_agreement&s=privacy
Author: 腾讯科技(深圳)有限公司
PackageName: 微信
PackageUrl: https://pc.weixin.qq.com/?lang=zh_CN
License: 免费软件
LicenseUrl: https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_agreement&s=default
Copyright: Copyright © 2021 Tencent. All Rights Reserved.
# CopyrightUrl: 
ShortDescription: 跨平台的通讯工具
Description: 一款跨平台的通讯工具。支持单人、多人参与。通过手机网络发送语音、图片、视频和文字。
# Moniker: 
Tags:
- 聊天
- 信息
- 分享
- 共享
- 语音
- 电话
- 朋友圈
- wechat
- weixin
- 腾讯
- tencent
ManifestType: locale
ManifestVersion: 1.0.0
