# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.1.0.schema.json

PackageIdentifier: Woyun.Wolai
PackageVersion: 1.1.3
PackageLocale: zh-CN
Publisher: 上海我云网络科技有限公司
PublisherUrl: https://www.wolai.com
PublisherSupportUrl: https://www.wolai.com/xhqeop8UHpVTMUSVmgz8nq
PrivacyUrl: https://www.wolai.com/az7AzNBmrPRjVZtdTVNi77
Author: 上海我云网络科技有限公司
PackageName: wolai
PackageUrl: https://www.wolai.com/product
License: © 2020 wolai.com® all rights reserved.
LicenseUrl: https://www.wolai.com/wolai/q5eyV15yEQPxBhjnFXyWtL
Copyright: © 2020 wolai.com® all rights reserved.
CopyrightUrl: https://www.wolai.com/wolai/q5eyV15yEQPxBhjnFXyWtL
ShortDescription: 用 “我来” 搭建一站式协作平台，不论团队或个人，开箱即用！
Description: 用 “我来” 搭建一站式协作平台，不论团队或个人，开箱即用！
# Moniker: 
Tags:
- notes
- wolai
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: locale
ManifestVersion: 1.1.0
