# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Woyun.Wolai
PackageVersion: 1.1.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://static2.wolai.com/dist/installers/wolai%20Setup%201.1.3.exe
  InstallerSha256: 26B99D5E020DCDC7DF22063580A76FD968B35BE15DF770D8D57039ECA9F57C97
ManifestType: installer
ManifestVersion: 1.1.0
