# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: alexx2000.DoubleCommander
PackageVersion: 1.0.2
PackageLocale: en-US
Publisher: Alexander Koblov
PublisherUrl: https://doublecmd.sourceforge.io
PublisherSupportUrl: https://doublecmd.h1n.ru
# PrivacyUrl: 
Author: Alexander Koblov
PackageName: Double Commander
PackageUrl: https://doublecmd.sourceforge.io
License: GNU GPL v2
LicenseUrl: https://sourceforge.net/p/doublecmd/code/HEAD/tree/trunk/doc/COPYING.txt
Copyright: Copyright (C) 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://sourceforge.net/p/doublecmd/code/HEAD/tree/trunk/doc/COPYING.txt
ShortDescription: Double Commander is a cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.
# Description: 
Moniker: doublecmd
Tags:
- commander
- cross-platform
- file-explorer
- file-manager
- foss
- manager
- open-source
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
