# Automatically updated by the winget bot at 2021/Dec/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: DucFabulous.UltraViewer
PackageVersion: 6.5.1
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://dl2.ultraviewer.net/UltraViewer_setup_6.2_en.exe
  InstallerSha256: E8FD64E8B7720B7F329A63157C128063CE1FCED8EF1107DCA9D857B9BD7C4149
ManifestType: installer
ManifestVersion: 1.0.0
