# Automatically updated by the winget bot at 2021/Dec/02
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Kafan.KafanInput
PackageVersion: 1.0.0.282
MinimumOSVersion: 10.0.0.0
FileExtensions:
- dict
Installers:
- InstallerLocale: zh-CN
  Architecture: neutral
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://input-download.kfsafe.cn/Kafan_Input.exe
  InstallerSha256: 6FA9E6B0EE2C86874B710D40A50A9A78F708162B958D4197C6E9ACCE978ADD91
  ProductCode: 'KafanInput'
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
