# Automatically updated by the winget bot at 2021/Dec/10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: LogMeIn.LastPass
PackageVersion: 4.86.0.2342
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.cloud.lastpass.com/windows_installer/LastPassInstaller.msi
  InstallerSha256: 52F261997DA2E0EE75B503317CBDDF4E53C1AD9E7987637EF002728E479695F7
  ProductCode: "{C56619A1-1EFF-4822-93FE-C2EBA825A249}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
