# Created with YamlCreate.ps1 v2.0.3 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Wondershare.PDFelement
PackageVersion: 8.3.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- pdf
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/pdfelement-pro_full5239.exe
  InstallerSha256: 4D6742190C1050A1EF11883FF7525EE0B55ACC813BEE00D79176A39BD6A0BBBA
ManifestType: installer
ManifestVersion: 1.1.0
