# Created using wingetcreate

PackageIdentifier: TheDocumentFoundation.LibreOffice.PreRelease
PackageVersion: 7.1.4.1
PackageLocale: en-US
Publisher: The Document Foundation
PackageName: LibreOffice-PreRelease
License: Mozilla Public License Version 2.0
ShortDescription: LibreOffice is a free and powerful office suite, and a successor to OpenOffice.org (commonly known as OpenOffice). Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.
ManifestType: defaultLocale
ManifestVersion: 1.0.0

