# Automatically updated by the winget bot at 2021/Dec/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Kakao.KakaoTalk
PackageVersion: 3.3.6.2992
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: ko-KR
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://app-pc.kakaocdn.net/talk/win32/KakaoTalk_Setup.exe
  InstallerSha256: 37B42C66F2FDD10D09A44700ED336D9F1CDFACC5BAA3ECC818687EE9A992EE08
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
