# Created with YamlCreate.ps1 v2.0.2 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Wondershare.PDFelement
PackageVersion: 8.3.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- pdf
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/pdfelement-pro_full5239.exe
  InstallerSha256: E3CAE55E45AC0B2F1CF1B41037A8E246474A0A94D9DE7CBA3713A4CD4CF76138
ManifestType: installer
ManifestVersion: 1.1.0
