# Automatically updated by the winget bot at 2021/Dec/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.171.5063
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x86
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
Installers:
- Architecture: x64
  InstallerUrl: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe
  InstallerSha256: 3887600DC4429AFDD04152384E786D27F5F8175168ABD4460F19C04E6752215F
ManifestType: installer
ManifestVersion: 1.1.0
