# Automatically updated by the winget bot at 2021/Dec/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.171.5063
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
