# Created with YamlCreate.ps1 v2.0.3 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Sandboxie.Classic
PackageVersion: 5.55.5
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.0/Sandboxie-Classic-x64-v5.55.0.exe
  InstallerSha256: DC8F0665A89360D49EC577232530A64E038AF011F4AE10849DA6B551495037EA
- Architecture: x86
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.0/Sandboxie-Classic-x86-v5.55.0.exe
  InstallerSha256: F1674F4CD21451033B36153778E5FA6E9E0930EFB5170DD661D1E7A5D991E906
ManifestType: installer
ManifestVersion: 1.1.0
