# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ImageMagick.ImageMagick
PackageVersion: 7.1.0.18
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- bmp
- eps
- gif
- jpg
- mif
- miff
- png
- svg
- tif
- tiff
- wmf
Installers:
- Architecture: x64
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-18-Q16-HDRI-x64-dll.exe
  InstallerSha256: B257C712D4E216A1303F6FD009E36F7BAE191B518E4213EDECDC55F584A86F63
  ProductCode: ImageMagick 7.1.0 Q16-HDRI (64-bit)_is1
- Architecture: x86
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-18-Q16-HDRI-x86-dll.exe
  InstallerSha256: 30444C638044F31B93CD02263CC711C8B865E01CE6B52CB5F48DB8D1B86E284A
  ProductCode: ImageMagick 7.1.0 Q16-HDRI (32-bit)_is1
ManifestType: installer
ManifestVersion: 1.1.0
