# Automatically updated by the winget bot at 2021/Nov/26
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: AntibodySoftware.WizFile
PackageVersion: 3.06
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://antibody-software.com/files/wizfile_3_04_setup.exe
  InstallerSha256: 6916519349E0337B3FCAC02E3C0747716B0FB29E2CD0BEC9C4AF7DD6F4BF5208
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
