# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Grammarly.ForWindows
PackageVersion: 1.0.1.110
PackageLocale: en-US
Publisher: Grammarly Inc.
PublisherUrl: https://www.grammarly.com/
# PublisherSupportUrl: 
PrivacyUrl: https://www.grammarly.com/privacy-policy
Author: Grammarly Inc.
PackageName: Grammarly for Windows
PackageUrl: https://www.grammarly.com/native/windows
License: Copyright (c) Grammarly Inc.
LicenseUrl: https://www.grammarly.com/terms
Copyright: Copyright (c) Grammarly Inc.
CopyrightUrl: https://www.grammarly.com/terms
ShortDescription: Harness the power of Grammarly on your desktop
# Description: 
Moniker: grammarly
Tags:
- checker
- english
- grammar
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
