# Automatically updated by the winget bot at 2021/Dec/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.1.0.schema.json

PackageIdentifier: TTKN.CNKIExpress
PackageVersion: 0.1.14
PackageLocale: zh-CN
Publisher: 同方知网（北京）技术有限公司
PublisherUrl: https://cnki.net
PublisherSupportUrl: https://m.cnki.net/mcnkidown/use-help.html
Author: 同方知网（北京）技术有限公司
PackageName: 全球学术快报
PackageUrl: https://m.cnki.net/mcnkidown/
License: 专有软件
Copyright: © CNKI INC
ShortDescription: 文献整合，热点速递
Description: 全球学术快报整合学术交流、阅读、问答、设备同步、个性化定制、智能推送、即时通讯等功能于一体，让学术更高效、更便捷。
Tags:
- 快报
- 文献
- 学术
- 阅读
- 知网
- CNKI
ManifestType: locale
ManifestVersion: 1.1.0
