# Created with YamlCreate.ps1 v2.0.3 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Tonec.InternetDownloadManager
PackageVersion: 6.40.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /skipdlgs
  SilentWithProgress: /skipdlgs
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.internetdownloadmanager.com/idman639build8.exe
  InstallerSha256: C9971A1D6E83B6B03C6D6B6C23FD121683AD6498B5AE722F5C1FE80A3BC2D5EE
ManifestType: installer
ManifestVersion: 1.1.0
