# Created with YamlCreate.ps1 v2.0.2 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome.Beta
PackageVersion: 97.0.4692.36
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 625FEF7205D35203D9CE273C4F63758AD2AAF7BF4FBFA3B747AE608F343E7A3C
  ProductCode: '{E238391E-A68B-3C12-A3C9-BB76FBC27D41}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 34E4968D42F245E4CC80C635670D15BBC81C4B91D578125C52AB6CE3C100C79D
  ProductCode: '{B9D80328-6BAD-389F-8683-A5478369DA35}'
ManifestType: installer
ManifestVersion: 1.1.0
