# Created with YamlCreate.ps1 v2.0.2 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Viber.Viber
PackageVersion: 16.6.0.0
PackageLocale: en-US
Publisher: Viber Media S.a.r.l
PublisherUrl: https://www.viber.com/en/
PublisherSupportUrl: https://help.viber.com/en
PrivacyUrl: https://www.viber.com/en/terms/viber-privacy-policy/
Author: Viber Media Inc.
PackageName: Viber
PackageUrl: https://www.viber.com/en/
License: Proprietary
LicenseUrl: https://www.viber.com/en/terms/viber-terms-use/
Copyright: Copyright Viber Media Inc.
CopyrightUrl: https://www.viber.com/en/terms/viber-terms-use/
ShortDescription: Viber is a mobile application that lets you make free phone calls and send text messages to anyone who also has the application installed. You can call or text any Viber user, anywhere in the world, for free.
Description: Viber is a mobile application that lets you make free phone calls and send text messages to anyone who also has the application installed. You can call or text any Viber user, anywhere in the world, for free.
Moniker: viber
Tags:
- voip
- voice
- chat
- voice-chat
- text-messaging
- group-chat
- phone
- messaging
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
