# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: libjpeg-turbo.libjpeg-turbo-gcc
PackageVersion: 2.1.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: uninstallPrevious
Commands:
- cjpeg
- djpeg
- jpegtran
- rdjpgcom
- tjbench
- wrjpgcom
Installers:
- Architecture: x64
  InstallerUrl: https://sourceforge.net/projects/libjpeg-turbo/files/2.1.2/libjpeg-turbo-2.1.2-gcc64.exe/download
  InstallerSha256: 51CF3E9029BF5001E55615AEF87BCA7F3ECE1A638B6EDB9E4ED717EE7EA2E7D9
  ProductCode: 'libjpeg-turbo-gcc64 2.1.2'
- Architecture: x86
  InstallerUrl: https://sourceforge.net/projects/libjpeg-turbo/files/2.1.2/libjpeg-turbo-2.1.2-gcc.exe/download
  InstallerSha256: 52B74A349E2A82CA41F3199BC92A5841E55AB5CFCA00DFAD224A7BD7E7910A52
  ProductCode: 'libjpeg-turbo-gcc 2.1.2'
ManifestType: installer
ManifestVersion: 1.1.0
