# Created with YamlCreate.ps1 v2.0.4 $debug=NVS1.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ksnip.ksnip.Continuous
PackageVersion: 1.10.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
FileExtensions:
- bmp
- gif
- jpg
- png
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ksnip/ksnip/releases/download/continuous/ksnip-1.10.0-continuous.msi
  InstallerSha256: FC3955AB9766F3905FE9A6BFAA1DA7A8FA2BBA169323CA92FB385DA39E91A2FC
  ProductCode: '{B08A0F29-F97E-4C49-A3F0-4E695E3A4CE2}'
ManifestType: installer
ManifestVersion: 1.1.0
