# Created with YamlCreate.ps1 v2.0.4 $debug=NVS1.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.1.0.schema.json

PackageIdentifier: ksnip.ksnip.Continuous
PackageVersion: 1.10.0
PackageLocale: en-US
Publisher: ksnip
PublisherUrl: http://ksnip.org/
PublisherSupportUrl: https://github.com/ksnip/ksnip/issues
# PrivacyUrl: 
Author: Damir Porobic
PackageName: ksnip (Continuous)
PackageUrl: https://github.com/ksnip/ksnip/
License: GPL-2.0
LicenseUrl: https://github.com/ksnip/ksnip/blob/master/LICENSE.txt
# Copyright: 
# CopyrightUrl: 
ShortDescription: Ksnip is a Qt-based cross-platform screenshot tool that provides many annotation features for your screenshots
# Description: 
# Moniker: 
Tags:
- qt
- screenshot
- tool
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
