# Automatically updated by the winget bot at 2021/Dec/07
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: RingCentral.RingCentral
PackageVersion: 21.4.26.2463
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://app.ringcentral.com/download/RingCentral-x64.msi
  InstallerSha256: 440440C22E648B95464D2087AAB7F85F6AFB9B2C0CBF618654B290207D5B84A5
  ProductCode: '{9ECC8195-3789-474B-92A6-CE84BA94FADF}'
ManifestType: installer
ManifestVersion: 1.0.0
