# Automatically updated by the winget bot at 2021/Nov/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: ArduinoSA.IDE.beta
PackageVersion: 2.0.0-beta.12
PackageLocale: en-US
Publisher: Arduino SA
PackageName: Arduino IDE Beta
License: GNU LGPL
ShortDescription: The open-source Arduino Software (IDE) makes it easy to write code and upload it to the board. This software can be used with any Arduino board.
Moniker: arduino-beta
ManifestType: defaultLocale
ManifestVersion: 1.0.0
