# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.GitCredentialManagerCore
PackageVersion: 2.0.632.34631
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /NORESTART
UpgradeBehavior: install
Installers:
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.632/gcmcore-win-x86-2.0.632.34631.exe
  InstallerSha256: B08EB15DD52472E82B74F010E229A5A36BC7876E16A8E762CE58BDD6829FE3E4
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.632/gcmcoreuser-win-x86-2.0.632.34631.exe
  InstallerSha256: 642C970D37CB048C8305019167EABB903CAF58C4CFC56B5E1B84F34390172799
ManifestType: installer
ManifestVersion: 1.1.0
