# Created with YamlCreate.ps1 v2.0.3 $debug=NVS1.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: rammichael.Textify
PackageVersion: 1.8.8
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://rammichael.com/downloads/textify_setup.exe
  InstallerSha256: 8312EC7905BD0F6DFC9E2151C9E246B32A77CCE906C189EBEF733B1732396FAC
  ProductCode: Textify
ManifestType: installer
ManifestVersion: 1.1.0
