# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: workman-layout.workman
PackageVersion: 2.0.0
PackageLocale: en-US
Publisher: Workman-Layout
PublisherUrl: https://github.com/workman-layout
PackageName: Workman (US)
PackageUrl: https://workmanlayout.org/
License: Freeware
LicenseUrl: https://github.com/workman-layout/Workman/blob/master/LICENSE
ShortDescription: Workman keyboard layout
Description: Workman keyboard layout originally proposed by OJ Bucao at https://workmanlayout.org.
Moniker: workman
Tags:
- keyboard
- layout
- workman-us
ManifestType: defaultLocale
ManifestVersion: 1.0.0

