# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Yubico.Authenticator
PackageVersion: 5.1.0
PackageLocale: en-US
Publisher: Yubico AB
PublisherUrl: https://www.yubico.com/
PublisherSupportUrl: https://support.yubico.com
PrivacyUrl: https://www.yubico.com/support/terms-conditions/privacy-notice/
Author: Yubico AB
PackageName: Yubico Authenticator
PackageUrl: https://www.yubico.com/products/yubico-authenticator/
Copyright: Yubico © 2021. All Rights Reserved.
#CopyrightUrl: 
License: BSD-2-Clause License
LicenseUrl: https://raw.githubusercontent.com/Yubico/yubioath-desktop/master/COPYING
ShortDescription: Authenticator to generate 2-step verification codes using your YubiKey
Description: Authenticator to generate 2-step verification codes using your YubiKey
Moniker: yubioath
Tags:
- 2fa
- security
- auth
- totp
ManifestType: defaultLocale
ManifestVersion: 1.1.0