# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Yubico.Authenticator
PackageVersion: 5.1.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerType: msi
  InstallerUrl: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.1.0-win64.msi
  InstallerSha256: 76685C8AE1783135DAA33D808F1B3CE34DD9ADE63013DF0F8FBC5FF3A5882997
  InstallerSwitches:
    Silent: /qn
    SilentWithProgress: /qb
    Custom: /norestart
  UpgradeBehavior: install
  ProductCode: '{E00E28E2-DED4-473D-B02A-4C22AE46902F}'
- InstallerLocale: en-US
  Architecture: x86
  Scope: machine
  InstallerType: msi
  InstallerUrl: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.1.0-win32.msi
  InstallerSha256: 1F3E08F201FAB6B3C774EB886410E9F9C6FEB0DEBEEE84411D27194945AC7468
  InstallerSwitches:
    Silent: /qn
    SilentWithProgress: /qb
    Custom: /norestart
  UpgradeBehavior: install
  ProductCode: '{15AF4599-A0CB-4012-B753-30D0D1355908}'
ManifestType: installer
ManifestVersion: 1.1.0