# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Recoupler.AudioBookConverter
PackageVersion: 5.6.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- aac
- flac
- m4a
- m4b
- mp3
- ogg
- wma
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/yermak/AudioBookConverter/releases/download/version_5.6.2/AudioBookConverter-All-Users-5.6.2.msi
  InstallerSha256: 189FB599E1D42F69CFA9DDAB8C4A428FC605A0CFFD35E1605AF01DC9E74B2B0D
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/yermak/AudioBookConverter/releases/download/version_5.6.2/AudioBookConverter-NoDeps-5.6.2.msi
  InstallerSha256: 3226DFE742666CAB822A044EC84163995CBCF6AFB02E7F01AC24BF6A829F631A
ManifestType: installer
ManifestVersion: 1.1.0
