# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Piriform.CCleaner.ProTrial
PackageVersion: "5.88"
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- ccleaner
FileExtensions:
- zzz
Installers:
- Architecture: neutral
  InstallerUrl: https://download.ccleaner.com/cctrialsetup.exe
  InstallerSha256: 885AD2A40812ABFDE6CCE86027989E34356B70B062782DD9E88E9911627C2ACE
ManifestType: installer
ManifestVersion: 1.1.0
