# Automatically updated by the winget bot at 2021/Nov/29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Figma.Figma
PackageVersion: 107.0.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.figma.com/win/FigmaSetup.exe
  InstallerSha256: 77F5070CC1A65C51C63ED9C6B63A0483E36EBC9337FAD481CDBFE1AA5B2DB477
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
