# Automatically updated by the winget bot at 2021/Dec/22
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Qoppa.PDFStudio
PackageVersion: 2021.1.2.0
MinimumOSVersion: 10.0.0.0
FileExtensions:
- pdf
InstallModes:
- interactive
- silent
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://download.qoppa.com/pdfstudio/PDFStudio_win64.msi
  InstallerSha256: 4BE4F0A9B6F9A2681DC046A58A489AE9025289E129D8A1EC13A939F50BB04EFE
  ProductCode: '{E70FE81B-3BF8-4B7E-AF92-5335A2B3F93A}'
  InstallerSwitches:
    Custom: /q
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
