PackageIdentifier: LutzRoeder.Netron
PackageVersion: 5.4.5
Platform:
- Windows.Desktop
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x86
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.4.5/Netron-Setup-5.4.5.exe
  InstallerSha256: C1DE932F156B7B883A48E15C3AF774FCFCE36BED756B5BE1EEBB52BE799FD817
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- Architecture: arm64
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v5.4.5/Netron-Setup-5.4.5.exe
  InstallerSha256: C1DE932F156B7B883A48E15C3AF774FCFCE36BED756B5BE1EEBB52BE799FD817
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
FileExtensions:
- armnn
- caffemodel
- cmf
- dnn
- h5
- hd5
- hdf5
- keras
- lite
- mar
- meta
- mlmodel
- mlpackage
- mnn
- model
- nb
- nn
- om
- onnx
- paddle
- param
- pb
- pbtxt
- pdmodel
- pdparams
- prototxt
- pt
- pth
- ptl
- rknn
- t7
- tfl
- tflite
- tmfile
- uff
- xmodel
ManifestType: installer
ManifestVersion: 1.0.0
