# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: JetBrains.CLion
PackageVersion: 213.6461.46
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/cpp/CLion-2021.3.1.exe
  InstallerSha256: C8C34E58D2E9F15B0DC738B5CA38E1023BA9E7FE889E8F6B8337E35D8C8954D3
ManifestType: installer
ManifestVersion: 1.1.0
