# Automatically updated by the winget bot at 2021/Nov/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: ESET.EndpointAntivirus
PackageVersion: 9.0.2032.2
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://download.eset.com/com/eset/apps/business/eea/windows/latest/eea_nt64.msi
  InstallerSha256: D1DAF46CF9C797E971B73D30BAE5CF4497D503AD14954A604170DEACDEDD6186
  ProductCode: '{232719D7-3D66-4761-A8F1-140A9DE18F11}'
ManifestType: installer
ManifestVersion: 1.0.0
