# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.KDEConnect
PackageVersion: 21.08.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/788/artifact/kdeconnect-kde-21.08.3-788-windows-msvc2019_64-cl.exe
  InstallerSha256: 4E37890A56188194634E27B84D36FE84691D39AC37B1E5F0734C99DCE1B681C7
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/788/artifact/kdeconnect-kde-21.08.3-788-windows-msvc2019_64-cl.exe
  InstallerSha256: 4E37890A56188194634E27B84D36FE84691D39AC37B1E5F0734C99DCE1B681C7
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.1.0
