# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: NewBreedSoftware.TuxPaint
PackageVersion: 0.9.27
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://sourceforge.net/projects/tuxpaint/files/tuxpaint/0.9.27/tuxpaint-0.9.27-1-windows-x86_64-installer.exe/download
  InstallerSha256: 03F9316DC2B676C02BE18F445EE00D643A2E605B26A608CDDD4AF3F3FC52E88A
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  Scope: user
  InstallerUrl: https://sourceforge.net/projects/tuxpaint/files/tuxpaint/0.9.27/tuxpaint-0.9.27-1-windows-x86_64-installer.exe/download
  InstallerSha256: 03F9316DC2B676C02BE18F445EE00D643A2E605B26A608CDDD4AF3F3FC52E88A
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://sourceforge.net/projects/tuxpaint/files/tuxpaint/0.9.27/tuxpaint-0.9.27-1-windows-i686-installer.exe/download
  InstallerSha256: 973C6CE8B79F4D15F858E94884D7AE674C5F82B36FDA9513468120DC246C07C7
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x86
  Scope: user
  InstallerUrl: https://sourceforge.net/projects/tuxpaint/files/tuxpaint/0.9.27/tuxpaint-0.9.27-1-windows-i686-installer.exe/download
  InstallerSha256: 973C6CE8B79F4D15F858E94884D7AE674C5F82B36FDA9513468120DC246C07C7
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.1.0
