# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Jabra.Direct
PackageVersion: 5.10.2
Platform:
- Windows.Desktop
MinimumOSVersion: 7.0.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /norestart
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://jabraxpressonlineprdstor.blob.core.windows.net/jdo/JabraDirectSetup.exe
  InstallerSha256: 6D80248E6E1FD326BCBDA64BD6E89E9F6E7F346D103A1F6E87B7BFDC89CBA687
ManifestType: installer
ManifestVersion: 1.1.0
