# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Eziriz.DotNetReactor
PackageVersion: 6.8.0.0
PackageLocale: en-US
Publisher: Eziriz
PublisherUrl: https://www.eziriz.com
PublisherSupportUrl: https://www.eziriz.com/support.htm
# PrivacyUrl: 
Author: Eziriz
PackageName: .NET Reactor
PackageUrl: https://www.eziriz.com/dotnet_reactor.htm
License: Proprietary
# LicenseUrl: https://www.eziriz.com/help/license_agreement.html
Copyright: Copyright © 2003 - 2021 Eziriz
# CopyrightUrl: https://www.eziriz.com/help/license_agreement.html
ShortDescription: .NET Reactor is a powerful code protection and software licensing system for software written for the .NET Framework, and supports all languages that generate .NET assemblies.
Description: .NET Reactor is a powerful code protection and software licensing system for software written for the .NET Framework, and supports all languages that generate .NET assemblies.
Moniker: dotnetreactor
Tags:
- .net
- obsfucation
- reactor
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
