# Automatically updated by the winget bot at 2021/Nov/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: RingCentral.RingCentral
PackageVersion: 21.4.25.2401
PackageLocale: en-US
Publisher: RingCentral
PackageName: RingCentral
License: copyright (c) ringcentral
ShortDescription: Team messaging, video meetings, and a business phone.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
