# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: PTRTECH.UVtools
PackageVersion: 2.26.0
PackageLocale: en-US
Publisher: PTRTECH
PackageName: UVtools
License: AGPL-3.0 License
ShortDescription: MSLA/DLP, file analysis, calibration, repair, conversion and manipulation
ManifestType: defaultLocale
ManifestVersion: 1.0.0

