# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Qalculate.Qalculate
PackageVersion: 3.22.0
MinimumOSVersion: 6.1.7600
InstallerType: msi
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Qalculate/libqalculate/releases/download/v3.22.0/qalculate-3.22.0-i386.msi
  InstallerSha256: 6DFBF5A8F7ED9F548067CD0518CFDA1FD3DFA4A62DEACB14084181573CE9A66C
- Architecture: x64
  InstallerUrl: https://github.com/Qalculate/libqalculate/releases/download/v3.22.0/qalculate-3.22.0-x64.msi
  InstallerSha256: E70120CD9F4305FD22373DBE8B7B80B947B4513BF6C2A245326B80D7B07DE33E
ManifestType: installer
ManifestVersion: 1.1.0
