# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: utools.utools
PackageVersion: 2.4.3
PackageLocale: en-US
Publisher: 福州猿力信息科技有限公司
PublisherUrl: https://u.tools/
# PublisherSupportUrl: 
# PrivacyUrl: 
Author: 福州猿力信息科技有限公司
PackageName: uTools
PackageUrl: https://u.tools/
License: Copyright (c) 福州猿力信息科技有限公司
# LicenseUrl: 
Copyright: Copyright (c) 福州猿力信息科技有限公司
# CopyrightUrl: 
ShortDescription: Your productivity toolkit
# Description: 
Moniker: utools
Tags:
- automation
- launcher
- search
- shortcut
- tools
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
