# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: utools.utools
PackageVersion: 2.4.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://publish.u-tools.cn/version2/uTools-2.4.3.exe
  InstallerSha256: BE57BBBDC90B38244F2E34D036D7A85B143940E41E1BDC8A296B203FDC18D0D4
ManifestType: installer
ManifestVersion: 1.1.0
