# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: NoMachine.NoMachineClient
PackageVersion: 7.7.4
PackageLocale: en-US
Publisher: NoMachine S.a.r.l.
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: NoMachine Enterprise
PackageUrl: https://nomachine.com/
License: Commercial
# LicenseUrl: 
# Copyright: 
# CopyrightUrl: 
ShortDescription: Free remote desktop for everybody (Client only)
# Description: 
Moniker: nomachine-enterprise
Tags:
- nomachine
- remote-access
- remote-desktop
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
