# Automatically updated by the winget bot at 2021/Dec/18
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Poly.PlantronicsHub
PackageVersion: 3.24.53436.35631
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://www.poly.com/content/dam/www/software/PlantronicsHubInstaller.exe
  InstallerSha256: 3F8C6A94FEF600565AEA48F6FE682574712914B8FA19126F7B1000740A8FB4D7
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
