# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Caphyon.AdvancedInstaller
PackageVersion: "19.0"
PackageLocale: en-US
Publisher: Caphyon
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: Advanced Installer
PackageUrl: https://AdvancedInstaller.com/
License: © Caphyon 2002 - 2020 Ltd. All rights reserved.
LicenseUrl: https://www.advancedinstaller.com/eula.html
# Copyright: 
# CopyrightUrl: 
ShortDescription: Advanced Installer is a powerful, yet easy to use, Windows Installer authoring tool which helps you create .MSI installs in minutes.
# Description: 
Moniker: advinst
# Tags: 
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
