# Automatically updated by the winget bot at 2021/Dec/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Wondershare.DemoCreator
PackageVersion: 5.4.0.14
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download.wondershare.com/cbs_down/democreator_full7743.exe
  InstallerSha256: 70E5F41F2697BBF87F120E2E5F743E7BB734F30E0F19E19039727FE99286CD0C
ManifestType: installer
ManifestVersion: 1.0.0
