# Created with YamlCreate.ps1 v2.0.3 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Sandboxie.Plus
PackageVersion: 1.0.0.0.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.0/Sandboxie-Plus-x64-v1.0.0.exe
  InstallerSha256: 79EF62C09E06D3915587F815062533428B2F79F83E1280C60CF6D369CFA8F8F5
- Architecture: x86
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.0/Sandboxie-Plus-x86-v1.0.0.exe
  InstallerSha256: E481CE3D1CD8A26128E880894623F03F74C00FE6FF26694F15649972E714C1AE
ManifestType: installer
ManifestVersion: 1.1.0
