# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Wondershare.Filmora
PackageVersion: 10.7.12.2
PackageLocale: en-US
Publisher: Wondershare Software
PublisherUrl: https://filmora.wondershare.com/
PublisherSupportUrl: https://support.wondershare.com
PrivacyUrl: https://www.wondershare.com/privacy.html
# Author: 
PackageName: Wondershare Filmora X
PackageUrl: https://filmora.wondershare.com
License: Proprietary
LicenseUrl: https://www.wondershare.com/company/end-user-license-agreement.html
Copyright: Copyright © 2021 Wondershare.
CopyrightUrl: https://www.wondershare.com/company/end-user-license-agreement.html
ShortDescription: Intuitive video editing
# Description: 
Moniker: filmora
Tags:
- filmora
- video-editor
- wondershare
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
