# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: RARLab.WinRAR.Beta
PackageVersion: 6.10.2
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Commands:
- winrar
FileExtensions:
- RAR
- ZIP
- 7Z
- ARJ
- BZ2
- CAB
- GZ
- ISO
- JAR
- LZ
- LZH
- TAR
- UUE
- XZ
- Z
- ZIPX
- 001
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  InstallerUrl: https://www.rarlab.com/rar/winrar-x64-610b2.exe
  InstallerSha256: 230F13442AA06F64F24F8E27F0CAF938F2B44EDD9825A1381CCF6D42CC7DFF09
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  InstallerUrl: https://www.rarlab.com/rar/winrar-x32-610b2.exe
  InstallerSha256: B1F92634D2D50028CBEBE0014EE969835D0FAF0DB4E00FA4A1A61ACA0732E13E
ManifestType: installer
ManifestVersion: 1.0.0

