# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: JetBrains.YouTrack
PackageVersion: 21.4.36872
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/charisma/youtrack-2021.4.36872.msi
  InstallerSha256: B617080D714C6A381E69C7F032C8ADE6D589A8E1B69E72B02A255DDE96CDC3C8
  ProductCode: '{4D0A252A-0491-49FD-B2A4-1BB190DE5FE4}'
ManifestType: installer
ManifestVersion: 1.1.0
