# Automatically updated by the winget bot at 2021/Dec/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: TunnelBear.TunnelBear
PackageVersion: 4.4.8.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015Redist-x86
Installers:
- Architecture: x86
  InstallerUrl: https://tunnelbear.s3.amazonaws.com/downloads/pc/public/TunnelBear-Installer.exe
  InstallerSha256: DD30F6DAD06DB6B69F9791A597C1339CA5DD8E02FBCE549A2AF54254B72A4612
ManifestType: installer
ManifestVersion: 1.0.0
