# Created with YamlCreate.ps1 v2.0.4 $debug=NVS0.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Stardock.Start11
PackageVersion: "1.01"
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://cdn.stardock.us/downloads/public/software/start/Start11_setup_sd.exe
  InstallerSha256: 9E44657EEA5847A98FB5D17B7F6A624FEFC1F28E6CF73B2665A289DD8944B294
ManifestType: installer
ManifestVersion: 1.1.0
