# Created with YamlCreate.ps1 v2.0.3 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: calibre.calibre
PackageVersion: 5.33.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- azw
- azw3
- docx
- epub
- fb2
- fbz
- html
- lit
- mobi
- odt
- pdb
- pdf
- prc
- rtf
- txt
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/kovidgoyal/calibre/releases/download/v5.33.2/calibre-5.33.2.msi
  InstallerSha256: 51D2C55C15FBE0BF6A77CD51CEF4951BF5A87966DFB7AA835F9B607AA8F7D531
  ProductCode: '{A82BE2C7-BF65-4806-A40D-944FF1CE9843}'
- Architecture: x64
  InstallerUrl: https://github.com/kovidgoyal/calibre/releases/download/v5.33.2/calibre-64bit-5.33.2.msi
  InstallerSha256: E2F97B11253B543D4766466C423FEC58E29941565C1F3DD5DFD00E56D8CD1095
  ProductCode: '{6663A21A-9018-4921-84A6-033C9EEC885F}'
ManifestType: installer
ManifestVersion: 1.1.0
