# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: OpenRPAApS.OpenRPA
PackageVersion: 1.3.35.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/open-rpa/openrpa/releases/download/1.3.35/OpenRPA.msi
  InstallerSha256: 19ACCEE3A99C6B7FB7138920C3B1A97961AAB3F047139728F0F646913A2DE75D
  ProductCode: '{F82B11B6-B6FE-4A3A-8A22-E8D4A5E735F5}'
ManifestType: installer
ManifestVersion: 1.1.0
