# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: AIMP.AIMP
PackageVersion: v5.01.2356, 22.12.2021
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /AUTO /SILENT
  SilentWithProgress: /AUTO
  Upgrade: /UPDATE
UpgradeBehavior: install
Commands:
- AIMP
FileExtensions:
- .spx
- aac
- ac3
- ape
- cda
- dts
- flac
- it
- m4a
- m4b
- midi
- mo3
- mod
- mp1
- mp2
- mp3
- mpc
- mtm
- ofr
- ogg
- opus
- rmi
- s3m
- tak
- tta
- umx
- wav
- wma
- wv
- xm
Installers:
- Architecture: x86
  InstallerUrl: https://aimp.ru/files/windows/builds/aimp_5.01.2356.exe
  InstallerSha256: D75F4BA768BF8F738AA3E268DE784F891BB539BC7058D70A10ABBA2FB8793412
ManifestType: installer
ManifestVersion: 1.1.0
