# Created with YamlCreate.ps1 v2.0.4 $debug=NVS1.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: sprout2000.LeafView
PackageVersion: 1.6.3.0
MinimumOSVersion: 10.0.0.0
InstallerType: appx
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
PackageFamilyName: 18155sprout2000.LeafView_n6bpymebb9kzw
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sprout2000/leafview/releases/download/v1.6.3/LeafView-1.6.3-win32-x64.appx
  InstallerSha256: 14ABB3C5134A50A12C0AF622E2E40FE81C4A5818742538B49CFE4592556E4E8D
  SignatureSha256: 5ABA4859B8EFF5F579C39D997A60A0C562C497745F4786E6D033E81473B20975
ManifestType: installer
ManifestVersion: 1.1.0
