# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: AutomatedLab.AutomatedLab
PackageVersion: "5.40"
PackageLocale: en-US
Publisher: AutomatedLab Team
PublisherUrl: https://automatedlab.org
PublisherSupportUrl: https://github.com/AutomatedLab/AutomatedLab/issues
# PrivacyUrl: 
Author: AutomatedLab Team
PackageName: AutomatedLab
PackageUrl: https://github.com/AutomatedLab/AutomatedLab
License: MIT License
LicenseUrl: https://github.com/AutomatedLab/AutomatedLab/blob/develop/LICENSE
Copyright: Copyright (c) 2021 Raimund Andrée, Jan-Hendrik Peters
CopyrightUrl: https://github.com/AutomatedLab/AutomatedLab/blob/develop/LICENSE
ShortDescription: AutomatedLab is a provisioning solution and framework that lets you deploy complex labs on HyperV and Azure with simple PowerShell scripts.
# Description: 
# Moniker: 
Tags:
- deployment
- powershell
- azure
- directory
- active-directory
- hyper
- exchange
- pki
- active
- scripted
- domain-controller
- automated-deployment
- scripted-deployment
- lab-machine hyperv 
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
