# Automatically updated by the winget bot at 2021/Dec/10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BitSum.ProcessLasso
PackageVersion: 10.4.1.18
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://dl.bitsum.com/files/processlassosetup64.exe
  InstallerSha256: 958CB9F82EAE6500DD4AA62CAD70901FE3EACF8DB7E7517824368B10CF474B29
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
