# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: PhraseExpress.PhraseExpress
PackageVersion: 15.0.93
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://www.phraseexpress.com/PhraseExpressSetup.exe
  InstallerSha256: 2EE729743477F05213200A1431E6A0D84372E7DA30966E2106D59D899ED2CE50
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://www.phraseexpress.com/PhraseExpressSetup.msi
  InstallerSha256: 4B6E9068F336520E6E2D0E8ACD049204B8CBFBFCB5785648843CC891B493FF65
ManifestType: installer
ManifestVersion: 1.0.0

