# Automatically updated by the winget bot at 2021/Dec/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ChronoplexSoftware.MyFamilyTree
PackageVersion: 11.1.5.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- aft
- afz
- agz
- aq
- dat
- family
- familyx
- familyxs
- fbk
- fdb
- fow
- ftb
- ftw
- gdz
- ged
- indiv2.dat
- mft
- nam
- paf
- pjc
- RM8
- RMB8
- rmg
- rmgb
- rmgc
- sqz
- tmg
- tre
- uzed
- ver
- zed
- zip
Installers:
- Architecture: x64
  InstallerUrl: https://chronoplexsoftware.com/myfamilytree/downloads/myfamilytree11.1.3.0x64.msi
  InstallerSha256: 6EF56A1DF160CA95078E029684EB79911159E4B9CA811D2C7E7743CCD8E5BF7C
  ProductCode: '{59B3F330-D5B9-44A2-8375-D3617765DBC7}'
- Architecture: x86
  InstallerUrl: https://chronoplexsoftware.com/myfamilytree/downloads/myfamilytree11.1.3.0.msi
  InstallerSha256: 33673994DEA4AD6C2675EF74BBB0BFABB54FA22461AD1F9AE2CC0176DBEDD608
  ProductCode: '{D0835DC2-2A9B-401D-8D00-5576D7F32417}'
ManifestType: installer
ManifestVersion: 1.1.0
