# Automatically updated by the winget bot at 2021/Dec/01
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.167.5056
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x86
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
Installers:
- Architecture: x64
  InstallerUrl: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe
  InstallerSha256: C189FE6AF7C176C08CDEE95741E3CA83792F6FBF6B2EB61B84A6C78AAB34DE7B
ManifestType: installer
ManifestVersion: 1.1.0
