# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Recoupler.AudioBookConverter
PackageVersion: 5.6.1
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: msi
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- aac
- flac
- m4a
- m4b
- mp3
- ogg
- wma
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/yermak/AudioBookConverter/releases/download/version_5.6.1/AudioBookConverter-All-Users-5.6.1.msi
  InstallerSha256: F114607908827106B742BC724B1C61F659591EE85B4C721220C5179FAEB41F11
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/yermak/AudioBookConverter/releases/download/version_5.6.1/AudioBookConverter-NoDeps-5.6.1.msi
  InstallerSha256: AAA974B8671F3CDA09A4B8C105DDD8D6B0711A8FB56C5563828DB6CB2EBF19C1
ManifestType: installer
ManifestVersion: 1.1.0
