# Created with YamlCreate.ps1 v2.0.2 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Spotify.Spotify
PackageVersion: 1.1.73.517.gbef50fdb
PackageLocale: en-US
Publisher: Spotify AB
PublisherUrl: https://www.spotify.com
PublisherSupportUrl: https://support.spotify.com
PrivacyUrl: https://www.spotify.com/legal/privacy-policy
Author: Spotify AB
PackageName: Spotify
PackageUrl: https://www.spotify.com
License: Proprietary
LicenseUrl: https://www.spotify.com/us/legal/end-user-agreement
Copyright: Copyright © 2021 Spotify AB. All rights reserved.
CopyrightUrl: https://www.spotify.com/no-en/legal/end-user-agreement
ShortDescription: Spotify is a digital music service that gives you access to millions of songs.
# Description: 
Moniker: spotify
Tags:
- music
- streaming
- radio
- freeware
- cross-platform
- podcast
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
