# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Blade.Shadow
PackageVersion: 5.0.1020
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://update.shadow.tech/launcher/prod/win/x64/ShadowSetup.exe
  InstallerSha256: F221CA5F510F64FB1BA8817D8C7F9A438AD30E45A663081BE6C0A1EE25D9480B
- Architecture: x86
  InstallerUrl: https://update.shadow.tech/launcher/prod/win/x86/ShadowSetup.exe
  InstallerSha256: 9AB9A9CC7B9E54E4252CAF650D9AC2E64A63C3744A90D46F852EF06B81389809
ManifestType: installer
ManifestVersion: 1.1.0
