# Created with YamlCreate.ps1 v2.0.4 $debug=NVS1.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Logitech.GHUB
PackageVersion: 2021.13.2906
PackageLocale: en-US
Publisher: Logitech
PublisherUrl: https://www.logitechg.com/en-us/innovation/g-hub.html.html
# PublisherSupportUrl: 
PrivacyUrl: https://www.logitechg.com/en-us/legal/web-privacy-policy.html
Author: Logitech
PackageName: Logitech G HUB
PackageUrl: https://support.logi.com/hc/en-us/articles/360025298133
License: Proprietary
# LicenseUrl: 
Copyright: Copyright (c) 2021 Logitech. All rights reserved
# CopyrightUrl: 
ShortDescription: Logitech G HUB Software lets you customize Logitech G gaming devices.
# Description: 
Moniker: lghub
Tags:
- driver
- gaming
- ghub
- headset
- hub
- keyboard
- lghub
- logitech
- mouse
- utility
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
