# Created with YamlCreate.ps1 v2.0.4 $debug=NVS1.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Logitech.GHUB
PackageVersion: 2021.13.2906
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
