# yaml-language-server: =https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Igoravl.TfsCmdlets
PackageVersion: 2.1.4.2594
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: user
  InstallerUrl: https://github.com/igoravl/TfsCmdlets/releases/download/v2.1.4%2B2594.1/TfsCmdlets-2.1.4.msi
  InstallerSha256: 47E50B8F8007A5474C70A70F70D907A2C333C7241B5819CA67283A368238F099
  InstallerSwitches:
    Silent: /qn
    SilentWithProgress: /qb
  ProductCode: "{95EBFDD2-F07A-4F61-B831-D59074C59626}"
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

