# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Igoravl.TfsCmdlets
PackageVersion: 2.1.4.2594
PackageLocale: en-US
Publisher: Igor Abade V. Leite
PublisherUrl: https://github.com/igoravl/TfsCmdlets
PublisherSupportUrl: https://github.com/igoravl/TfsCmdlets/issues
# PrivacyUrl: 
Author: Igor Abade V. Leite
PackageName: TfsCmdlets
PackageUrl: https://tfscmdlets.dev/
License: MIT
LicenseUrl: https://github.com/igoravl/TfsCmdlets/blob/main/LICENSE.md
Copyright: Copyright (c) Igor Abade V. Leite
CopyrightUrl: https://github.com/igoravl/TfsCmdlets/blob/main/LICENSE.md
ShortDescription: PowerShell Cmdlets for Azure DevOps and Team Foundation Server
Description: TfsCmdlets is a PowerShell module which provides many commands to simplify automated interaction with Azure DevOps (Server & Services) and Team Foundation Server.
Moniker: tfscmdlets
Tags:
- tfscmdlets
- tfs
- vsts
- powershell
- azure
- azuredevops
- devops
- alm
- teamfoundationserver
# Agreements: 
ReleaseNotes: |
  Version 2.1.4 (30/Nov/2021)

  This release fixes a couple issues in Get-TfsIdentity and Invoke-TfsRestApi.

  Fixes

  - Error when using Get-TfsIdentity with Azure DevOps Services- Get-TfsIdentity is a cmdlet that helps to deal with legacy APIs, such as the Azure DevOps Security API. To fetch an identiy, it connected to a configuration server (the "root" of an Azure DevOps installation) and called the required API. However, connecting to a configuration server is not supported when using Azure DevOps Services. Now, when used with Azure DevOps Services, Get-TfsIdentity will use the collection (organization) scope for the API, whereas calls to the on-prem server still target the configuration server.

  - Error calling Invoke-TfsRestApi for alternate hosts under Windows PowerShell (Desktop)- There was a bug in the implementation of Invoke-TfsRestApi that caused it to fail when using alternate hosts in Windows PowerShell. This has been fixed.
ReleaseNotesUrl: https://github.com/igoravl/TfsCmdlets/blob/main/RELEASENOTES.md#version-214-30nov2021
ManifestType: defaultLocale
ManifestVersion: 1.1.0
